version: '2'
services:

        
        database:
                image: mysql:5.6
                command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/init.sql"
                restart: always
                volumes:
                        - ./dbconfig/init.sql:/tmp/init.sql:z # The z is to get passed SeLinux

                ports:
                        - "33061:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: changeme
                        MYSQL_DATABASE: keis
                        MYSQL_PASSWORD: changeme
                        MYSQL_USER: root
                        ON_CREATE_DB: keis

        # CONTAINS THE BACKEND DEPENDENCIES AND CODE
        backend:
                build:
                        context: ./KEIS
                        dockerfile: Dockerfile
                links:
                        - database:db
        
                working_dir: /var/www/backend
                volumes:
                        - ./KEIS:/var/www/backend
                depends_on:
                        - database
                
        # THIS CONTAINER SERVES THE BACKEND                
        web:
                build:
                        context: ./
                        dockerfile: web.dockerfile
                working_dir: /var/www
                volumes_from:
                        - backend
                ports: 
                        - 5000:5000


        # ANGULAR FRONTEND
        frontend:
                build:
                        context: ./KEIS-frontend-angular
                        dockerfile: Dockerfile
                depends_on:
                        - backend
                ports:
                        - 80:80
