version: '2'
services:
        backend:
                build:
                        context: ./KEIS
                        dockerfile: Dockerfile
        
                working_dir: /var/www
                volumes:
                        - ./KEIS:/var/www
                environment:
                        - "DB_PORT=3306"
                        - "DB_HOST=database"
                        - "DB_USERNAME=root"
                        - "DB_PASSWORD=changeme"


        
        database:
                image: mysql:5.6
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                volumes:
                        - dbdata:/var/lib/mysql

                ports:
                        - "33061:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: changeme
                        MYSQL_DATABASE: keis

        web:
                build:
                        context: ./
                        dockerfile: web.dockerfile
                working_dir: /var/www
                volumes_from:
                        - backend
                ports: 
                        - 80:80
volumes:
        dbdata:
